create extension if not exists pgcrypto;

create table if not exists public.boards (
  id uuid primary key default gen_random_uuid(),
  share_token text not null unique,
  title text not null default 'Scouting ShortList',
  season_id text not null default '2026',
  gender text not null default 'male' check (gender in ('male', 'female')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.board_meta (
  board_id uuid primary key references public.boards(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.board_slots (
  id bigint generated by default as identity primary key,
  board_id uuid not null references public.boards(id) on delete cascade,
  position_id text not null,
  rank int not null check (rank between 1 and 6),
  scenario text not null check (scenario in ('0-2', '2-5', '5-10', '10-20')),
  lane text not null check (lane in ('A1B1', 'A2', 'B1')),
  name text not null default '',
  player text not null default '',
  club text not null default '',
  age text not null default '',
  expiring text not null default '',
  player_id text not null default '',
  team_id text not null default '',
  competition_id text not null default '',
  updated_at timestamptz not null default now(),
  unique (board_id, position_id, rank, scenario, lane)
);

create index if not exists board_slots_board_idx on public.board_slots(board_id);
create index if not exists board_slots_position_idx on public.board_slots(board_id, position_id);
create index if not exists boards_token_idx on public.boards(share_token);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists boards_touch_updated_at on public.boards;
create trigger boards_touch_updated_at
before update on public.boards
for each row execute function public.touch_updated_at();

drop trigger if exists board_meta_touch_updated_at on public.board_meta;
create trigger board_meta_touch_updated_at
before update on public.board_meta
for each row execute function public.touch_updated_at();

drop trigger if exists board_slots_touch_updated_at on public.board_slots;
create trigger board_slots_touch_updated_at
before update on public.board_slots
for each row execute function public.touch_updated_at();

alter table public.boards enable row level security;
alter table public.board_meta enable row level security;
alter table public.board_slots enable row level security;
